CREATE table roles
(id int8 generated by default as identity,
name varchar(255),
primary key (id)
)
create table user_roles (user_id int8 not null, role_id int8 not null)
create table users (id int8 generated by default as identity, email varchar(255), password varchar(255), username varchar(255), primary key (id))
alter table if exists user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles
alter table if exists user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users

